import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {graphModel,graphState,moments as gm} from './graph-grow/state.js';
import {tokenModel,tokenState,tokenCell,moments as tm} from './token-stream/state.js';
const slots={hub:'Hub',...Object.fromEntries(Array.from({length:8},(_,i)=>['n'+(i+1),'N'+i]))};
for(const topology of ['star','chain','layers','mesh'])test('graph '+topology,()=>{const params={topology,path:'n1>hub>n4',seed:9,'camera.orbit_deg':30};const a=graphModel(slots,params),b=graphModel(slots,params);assert.deepEqual(a,b);for(const reduced of [false,true])for(const t of [0,.6,1.2,2,2.8,3.6,4.2,5.2,5.8,6,2.245]){const want=graphState(a,t,reduced);for(let u=0;u<6;u+=.016)graphState(a,u,reduced);assert.deepEqual(graphState(a,t,reduced),want);assert.ok(want.orbit<=Math.PI/6);if(reduced)assert.equal(want.orbit,0);}assert.equal(a.ids.length,9);assert.ok(a.edges.every(e=>e.every(id=>a.ids.includes(id))));});
for(const mode of ['fill','overflow','generate'])for(const token_count of [12,32,80])for(const capacity_ratio of [.5,1,1.3,1.5])test(`token ${mode} ${token_count} ${capacity_ratio}`,()=>{if(mode==='overflow'&&capacity_ratio<=1){assert.throws(()=>tokenModel({mode,token_count,capacity_ratio,seed:1}));return;}const m=tokenModel({mode,token_count,capacity_ratio,seed:1});assert.deepEqual(m,tokenModel(m.params));for(const reduced of [false,true])for(const t of [...tm,2.371,7]){const s=tokenState(m,t,reduced);tokenState(m,7,reduced);assert.deepEqual(tokenState(m,t,reduced),s);assert.ok(s.stored<=m.capacity);assert.ok(s.expelled<=Math.max(0,m.count-m.capacity));assert.ok(s.generated<=8);}if(mode==='overflow')assert.equal(tokenState(m,7).expelled,m.count-m.capacity);});
test('mapped semantic landmark spacing at maximum stretch',()=>{for(const [events,def,max]of [[gm,6,10],[tm,7,12]]){const all=[...events,def];assert.ok(all.every((x,i)=>!i||(x-all[i-1])*max/def<=2));}});
test('invalid and sparse graph paths',()=>{const p={topology:'star',path:'n1>hub>n4',seed:1,'camera.orbit_deg':0};assert.throws(()=>graphModel({hub:'Hub',n1:'A'},p));assert.throws(()=>graphModel(slots,{...p,path:'n1>n1>hub'}));assert.equal(graphModel({hub:'Hub',n1:'A',n4:'B'},p).ids.length,3);});
test('source contracts and vendored Three revision',async()=>{for(const id of ['graph-grow','token-stream']){const m=JSON.parse(await fs.readFile(new URL(`./${id}/asset.json`,import.meta.url)));assert.equal(m.kind,'module');assert.deepEqual(m.parameters,m.broll.params);for(const f of ['main.js','scene.js','state.js'])assert.doesNotMatch(await fs.readFile(new URL(`./${id}/${f}`,import.meta.url),'utf8'),/Math\.random\s*\(|Date\.now\s*\(|performance\.now\s*\(|requestAnimationFrame\s*\(/);const three=await fs.readFile(new URL(`./${id}/vendor/three.min.js`,import.meta.url),'utf8');assert.match(three,/160/);}});

import * as THREE from './graph-grow/vendor/three.min.js';
test('vendor exact revision and worst-size token containment',()=>{assert.equal(THREE.REVISION,'160');const geometry=new THREE.BoxGeometry(.23,.23,.23);const vertex=new THREE.Vector3();for(const count of [12,32,80])for(const ratio of [.5,1,1.3,1.5]){const capacity=Math.floor(count/ratio);for(let i=0;i<Math.min(capacity,count);i++){const object=new THREE.Object3D();object.position.set(...tokenCell(capacity,i));object.rotation.set(.12,.15,.08);object.scale.setScalar(1.1);object.updateMatrix();for(let j=0;j<geometry.attributes.position.count;j++){vertex.fromBufferAttribute(geometry.attributes.position,j).applyMatrix4(object.matrix);assert.ok(Math.abs(vertex.x)<1.15&&Math.abs(vertex.y)<1.2&&Math.abs(vertex.z)<.6);}}}geometry.dispose();});
