// HF_RUNTIME=<locked 0.8.27 iife> GSAP_FILE=<local gsap> CHROME_PATH=<chromium> node tests/explainer-browser.mjs
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { chromium } = createRequire(path.join(repo, '.studio/remotion/package.json'))('playwright-core');
const { HF_RUNTIME, GSAP_FILE, CHROME_PATH } = process.env;
assert(HF_RUNTIME && GSAP_FILE && CHROME_PATH, 'Set local runtime, GSAP and Chromium paths');
assert.equal(JSON.parse(await fs.readFile(path.resolve(HF_RUNTIME, '../../package.json'), 'utf8')).version, '0.8.27', 'Use the locked runtime');
const output = await fs.mkdtemp(path.join(os.tmpdir(), 'hf-explainer-'));
await fs.cp(path.join(repo, '.studio/runtime'), path.join(output, 'runtime'), { recursive: true });
await fs.copyFile(HF_RUNTIME, path.join(output, 'hf-runtime.js'));
await fs.copyFile(GSAP_FILE, path.join(output, 'gsap.js'));
const write = (name, value) => fs.writeFile(path.join(output, name), JSON.stringify(value));
const text = 'Hello!Next.';
const characters = Array.from(text, (char, i) => ({ char, aligned: char !== '!', start: char === '!' ? null : .5 + i * .3, end: char === '!' ? null : .8 + i * .3 }));
await write('runtime/cues.json', { schema_version: 1, text, characters, speech_intervals: [[.5, 2], [2.3, 3.8]] });
const assets = [];
for (const [kind, payload, dependencies] of [
  ['theme', { tokens: { colors: { text: '#17272c', accent: '#b72059' }, surface: { color: '#ffffff' }, typography: { body: 'sans-serif' } } }, []],
  ['background', { renderer: 'module', entry: 'module.js', parameters: { moods: [{ cue: 'Next', tint: '#dcebf7' }] } }, ['module.js']],
  ['character', { name: 'fixture', profile: 'Synthetic', series_style: 'Flat', reference: 'normal.png', default_state: 'normal', states: { normal: { file: 'normal.png', anchor: [32, 63], facing: 'right' }, point: { file: 'point.png', anchor: [32, 63], facing: 'left' } }, provenance: { source: 'Synthetic RGBA pixels generated by explainer-browser.mjs' } }, ['normal.png', 'point.png']],
]) {
  await fs.mkdir(path.join(output, kind));
  const entry = kind === 'character' ? 'character.json' : 'entry.json';
  await write(`${kind}/asset.json`, { schema_version: 2, id: kind, version: 1, kind, contract_version: 1, entry, dependencies });
  await write(`${kind}/${entry}`, payload);
  assets.push({ ref: `${kind}@v1`, kind, vendor_path: kind, package_sha256: 'fixture' });
}
await fs.copyFile(path.join(repo, 'tests/fixtures/explainer-background.js'), path.join(output, 'background/module.js'));
await write('appearance-lock.json', { schema_version: 2, contract_version: 2, resolver_version: 1, assets, mode: 'explainer', seed: 0,
  selection: { captions: true, theme: assets[0], background: assets[1], motion: {} }, parameters: { theme: {}, background: {}, motion: {} } });
const synth = spawnSync('python3', ['-c', `import pathlib, struct, zlib, wave, math, sys
root=pathlib.Path(sys.argv[1])
for name,color in [('normal',(20,150,100)),('point',(190,35,85))]:
 raw=b''.join(b'\\0'+b''.join(bytes((*color,255 if 8<x<56 and 4<y<63 else 0)) for x in range(64)) for y in range(64))
 def chunk(tag,data): return struct.pack('>I',len(data))+tag+data+struct.pack('>I',zlib.crc32(tag+data))
 (root/'character'/f'{name}.png').write_bytes(b'\\x89PNG\\r\\n\\x1a\\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',64,64,8,6,0,0,0))+chunk(b'IDAT',zlib.compress(raw))+chunk(b'IEND',b''))
for name,seconds,freq in [('speech',5,220),('sfx',.3,880)]:
 with wave.open(str(root/f'{name}.wav'),'wb') as wav:
  wav.setparams((1,2,24000,0,'NONE','not compressed'));wav.writeframes(b''.join(struct.pack('<h',int(3000*math.sin(2*math.pi*freq*i/24000))) for i in range(int(24000*seconds))))
`, output], { encoding: 'utf8' });
assert.equal(synth.status, 0, synth.stderr);
await fs.mkdir(path.join(output, 'media'));
for (const name of ['speech', 'sfx']) {
  const encode = spawnSync('ffmpeg', ['-v', 'error', '-y', '-i', path.join(output, name + '.wav'), path.join(output, 'media', name + '.mp3')], { encoding: 'utf8' });
  assert.equal(encode.status, 0, encode.stderr);
}
const sound = spawnSync('python3', ['-c', `import json, pathlib, sys
sys.path.insert(0,str(pathlib.Path(sys.argv[1])/'.studio'))
from explainer import sound_elements
root=pathlib.Path(sys.argv[2]); cues=json.loads((root/'runtime/cues.json').read_text())
plan={'bgm':{'ref':'music@v1','start_cue':'H','end_cue':{'token':'.','edge':'end'},'gain':.5},'sfx':[{'ref':'ping@v1','cue':'Next','event':'character points','tier':'accent','gain':.7}]}
assets={'music@v1':{'vendor_path':'media','metadata':{'kind':'media','entry':'speech.mp3'}},'ping@v1':{'vendor_path':'media','metadata':{'kind':'media','entry':'sfx.mp3','hit_offset':.1,'audio':{'duration':.3}}}}
html,tracks=sound_elements(plan,cues,assets)
print(json.dumps({'html':html,'tracks':tracks}))
`, repo, output], { encoding: 'utf8' });
assert.equal(sound.status, 0, sound.stderr);
const soundResult = JSON.parse(sound.stdout);
assert(Math.abs(Number(soundResult.tracks[1]['data-start']) - 2.2) < 1e-8, 'Generated SFX accounts for hit_offset');
await fs.writeFile(path.join(output, 'index.html'), `<!doctype html><meta charset="utf-8"><style>
body{margin:0}main{position:relative;width:100vw;height:100vh;overflow:hidden}[data-hf-layer]{position:absolute;inset:0}#background{z-index:0}#stage{z-index:1}#overlay{z-index:2}#text{z-index:3}#captions{z-index:4}#figure{position:absolute;left:20%;top:25%;width:128px;height:128px}#picture{position:absolute;left:65%;top:32%;width:64px;height:64px}h1{font:28px sans-serif;margin:8% 10%}
</style><script src="gsap.js"></script><script src="hf-runtime.js"></script>
${['cues', 'captions', 'figures', 'appearance', 'scene-binding'].map(n => '<script src="runtime/' + n + '.js"></script>').join('')}
<main data-composition-id="fixture" data-start="0" data-duration="5"><div id="background" data-hf-layer="background"></div><div id="stage" data-hf-layer="stage"><div id="figure"></div><img id="picture" src="character/normal.png"></div><div id="overlay" data-hf-layer="overlay"></div><div id="text" data-hf-layer="text"><h1>Explainer fixture</h1></div><div id="captions" data-hf-layer="captions"></div><audio src="speech.wav" class="clip" data-start="0" data-duration="5" data-track-index="1"></audio>${soundResult.html}</main>
<script>
const el=id=>document.getElementById(id);
window.__timelines={fixture:gsap.timeline({paused:true}).to({},{duration:5})};
window.ready=(async()=>{
 window.cues=await HarnessCues.load();window.appearance=await HarnessAppearance.load();HarnessAppearance.apply(document.querySelector('main'),appearance);
 const figureLock=innerWidth<innerHeight?{components:appearance.lock.assets.map(a=>({...a,asset_kind:a.kind,component_ref:a.ref}))}:appearance.lock;
 window.figures=await HarnessFigures.load(figureLock,{cues});
 window.figure=figures.figure(el('figure'),'character@v1').enter(.5).bounce('Next',{duration:1,amplitude:20}).state('Next','point').talk();
 figures.image(el('picture')).pan(1,{duration:2,x:-30}).zoom(1,{duration:2,scale:1.2}).squash(2,{duration:1}).idle(0,{duration:5,amplitude:3}).point(2,{duration:1});
 const background=await HarnessAppearance.mountBackground(el('background'),appearance,cues);
 const enabled=new URLSearchParams(location.search).get('captions')!=='off';
 if(!enabled)el('captions').remove();
 window.captions=HarnessCaptions.mount(el('captions'),cues,{ratio:innerWidth<innerHeight?'9:16':'16:9',enabled});
 window.binding=HarnessScene.bindExplainer({duration:5,captions,background,figures});await binding.seek(0);
})();
window.snapshot=()=>({figure:el('figure').outerHTML,picture:el('picture').outerHTML,captions:el('captions')?.innerHTML,background:el('background').querySelector('canvas').toDataURL()});
</script>`);
const server = http.createServer(async (request, response) => {
  try {
    const name = decodeURIComponent(new URL(request.url, 'http://localhost').pathname).slice(1) || 'index.html';
    const file = path.resolve(output, name); assert(file.startsWith(output + path.sep));
    response.setHeader('Content-Type', ({ '.js': 'application/javascript', '.json': 'application/json', '.png': 'image/png', '.wav': 'audio/wav', '.mp3': 'audio/mpeg' })[path.extname(file)] || 'text/html');
    response.end(await fs.readFile(file));
  } catch { response.writeHead(404).end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
let browser; const evidence = { scope: 'WSL runtime-only; no native Studio or physical audio acceptance', output, frames: [], errors: [] };
try {
  browser = await chromium.launch({ executablePath: CHROME_PATH, headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage(); page.on('pageerror', error => evidence.errors.push(error.message));
  await page.addInitScript(() => {
    const NativeContext = window.AudioContext;
    window.audioProbe = { contexts: [], gains: [], sources: [], media: [] };
    window.AudioContext = class extends NativeContext {
      constructor(...args) { super(...args); audioProbe.contexts.push(this); }
      createGain() {
        const node = super.createGain(), analyser = super.createAnalyser();
        analyser.fftSize = 2048; node.connect(analyser);
        audioProbe.gains.push({ node, analyser }); return node;
      }
      createBufferSource() {
        const node = super.createBufferSource(), start = node.start;
        node.start = function (...args) { audioProbe.sources.push({ args, duration: node.buffer?.duration }); return start.apply(this, args); };
        return node;
      }
      createMediaElementSource(el) { audioProbe.media.push(el); return super.createMediaElementSource(el); }
    };
    window.readAudioProbe = () => ({ contexts: audioProbe.contexts.map(c => ({ state: c.state, time: c.currentTime })), sources: audioProbe.sources,
      media: audioProbe.media.map(el => ({ src: el.currentSrc, time: el.currentTime, paused: el.paused, connected: el.isConnected })),
      gains: audioProbe.gains.map(({ node, analyser }) => {
        const data = new Float32Array(analyser.fftSize); analyser.getFloatTimeDomainData(data);
        return { gain: node.gain.value, rms: Math.sqrt(data.reduce((sum, v) => sum + v * v, 0) / data.length) };
      }) });
  });
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  for (const viewport of [{ width: 1280, height: 720 }, { width: 450, height: 800 }]) {
    await page.setViewportSize(viewport);
    const visit = async (suffix = '') => { await page.goto('http://127.0.0.1:' + server.address().port + suffix); await page.evaluate(() => ready); };
    await visit();
    const seek = async t => page.evaluate(async t => { const start = performance.now(); await __player.renderSeek(t); await window.__hfWaitForSeekCompletion?.(); return { t, milliseconds: performance.now() - start, state: snapshot() }; }, t);
    const states = []; const shots = [];
    for (const t of [2.65, 0, 1.25, 2.65]) {
      states.push(await seek(t));
      shots.push(await page.screenshot({ path: path.join(output, viewport.width + '-' + states.length + '.png') }));
    }
    assert.deepEqual(states[0].state, states[3].state); assert(shots[0].equals(shots[3]), 'Random seeks produce identical pixels');
    assert.notDeepEqual(states[0].state, states[2].state);
    const pixels = await page.evaluate(async base64 => {
      const img = new Image(); img.src = 'data:image/png;base64,' + base64; await img.decode();
      const canvas = document.createElement('canvas'); canvas.width = img.width; canvas.height = img.height;
      const ctx = canvas.getContext('2d'); ctx.drawImage(img, 0, 0); const rgba = ctx.getImageData(0, 0, img.width, img.height).data;
      let colored = 0; for (let i = 0; i < rgba.length; i += 4) if (rgba[i] > 150 && rgba[i + 1] < 100 || rgba[i] < 50 && rgba[i + 1] > 100) colored++;
      return colored;
    }, shots[0].toString('base64'));
    assert(pixels > 1000, 'Rendered PNGs and canvas must contain visible subjects');
    await visit();
    for (let t = 0; t < 2.65; t += .1) await seek(t);
    assert.deepEqual((await seek(2.65)).state, states[0].state, 'Sequential and direct seek match');
    const checks = await page.evaluate(() => {
      const error = fn => { try { fn(); return ''; } catch (e) { return e.message; } };
      const ambiguous = HarnessCues.from({ schema_version: 1, text: 'aa', characters: [{ char: 'a', start: 0, end: 1, aligned: true }, { char: 'a', start: 1, end: 2, aligned: true }] });
      const line = el('captions').firstChild.getBoundingClientRect();
      return { missing: error(() => cues.find('absent')), unaligned: error(() => cues.find('!')), ambiguous: error(() => ambiguous.find('a')), nth: ambiguous.find({ token: 'a', nth: 2 }), window: ambiguous.find('a', { within: [1, 2], edge: 'end' }), outside: error(() => figures.figure(el('figure'), 'unknown@v1')), safe: line.left >= innerWidth * .09 && line.right <= innerWidth * .91 && line.bottom <= innerHeight * .91, images: [...document.images].every(i => i.complete && i.naturalWidth > 0) };
    });
    assert.deepEqual(checks, { missing: 'cue_not_found', unaligned: 'cue_unaligned', ambiguous: 'cue_ambiguous', nth: 1, window: 2, outside: 'figure_asset_outside_closure', safe: true, images: true });
    const highlighted = await page.evaluate(() => [...el('captions').querySelectorAll('span')].filter(e => e.dataset.highlighted === 'true').map(e => e.textContent).join(''));
    assert(highlighted.includes('!'), 'Unaligned punctuation highlights with following aligned character');
    const punctuation = await page.evaluate(async () => {
      await binding.seek(2.29);
      const before = [...el('captions').querySelectorAll('span')].find(s => s.textContent === '!').dataset.highlighted;
      await binding.seek(2.3);
      return { before, after: [...el('captions').querySelectorAll('span')].find(s => s.textContent === '!').dataset.highlighted, groups: captions.groups.map(g => g.chars.map(c => c.char).join('')) };
    });
    assert.deepEqual(punctuation, { before: 'false', after: 'true', groups: ['Hello!', 'Next.'] });
    await seek(1.25); await page.evaluate(() => __player.play()); await page.waitForTimeout(180);
    const webAudio = await page.evaluate(() => readAudioProbe());
    await page.evaluate(() => __player.pause());
    const audio = await page.evaluate(() => [...document.querySelectorAll('audio')].map(a => ({ time: a.currentTime, paused: a.paused, readyState: a.readyState, error: a.error?.message || null })));
    evidence.frames.push({ viewport, states, checks, pixels, audio, webAudio });
    assert(audio.every(a => !a.error && a.paused), JSON.stringify(audio));
    assert(webAudio.contexts.some(c => c.state === 'running' && c.time > 0), 'HF uses a running WebAudio clock');
    assert(webAudio.sources.length + webAudio.media.length >= 2, 'HF schedules narration and generated BGM through WebAudio');
    assert(webAudio.gains.some(g => g.rms > .001), 'Real WebAudio graph produces nonzero PCM');
    assert(webAudio.gains.some(g => Math.abs(g.gain - .25) < .001), 'Generated speech ducking reaches group GainNode');
    const musicInput = webAudio.gains.find(g => Math.abs(g.gain - .5) < .001);
    const musicOutput = webAudio.gains.find(g => Math.abs(g.gain - .25) < .001);
    assert(musicInput.rms > .001 && Math.abs(musicOutput.rms / musicInput.rms - .25) < .02, 'Actual BGM PCM is attenuated to one quarter');
    await seek(2.25); await page.evaluate(() => __player.play()); await page.waitForTimeout(120);
    const sfxAudio = await page.evaluate(() => readAudioProbe());
    await page.evaluate(() => __player.pause());
    evidence.frames.at(-1).sfxAudio = sfxAudio;
    assert(sfxAudio.gains.some(g => Math.abs(g.gain - .7) < .001 && g.rms > .001), 'Generated SFX enters the real audio graph at its scheduled cue');
    await visit('/?captions=off'); await seek(2.65); assert.equal(await page.locator('[data-hf-layer="captions"]').count(), 0);
    await page.evaluate(() => { binding.dispose(); appearance.dispose(); });
    assert.equal(await page.locator('canvas').count(), 0);
  }
  assert.deepEqual(evidence.errors, []);
  evidence.passed = true;
} finally {
  await browser?.close(); await new Promise(resolve => server.close(resolve));
  await fs.writeFile(path.join(output, 'evidence.json'), JSON.stringify(evidence, null, 2)); console.log(output);
}
